CREATE TABLE `imu_y45` (
	`number` BIGINT NULL DEFAULT NULL,
	`remark` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`time` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`ax` FLOAT NULL DEFAULT NULL,
	`ay` FLOAT NULL DEFAULT NULL,
	`az` FLOAT NULL DEFAULT NULL,
	`gx` FLOAT NULL DEFAULT NULL,
	`gy` FLOAT NULL DEFAULT NULL,
	`gz` FLOAT NULL DEFAULT NULL,
	`mx` FLOAT NULL DEFAULT NULL,
	`my` FLOAT NULL DEFAULT NULL,
	`mz` FLOAT NULL DEFAULT NULL,
	`roll` FLOAT NULL DEFAULT NULL,
	`yaw` FLOAT NULL DEFAULT NULL,
	`pitch` FLOAT NULL DEFAULT NULL,
	INDEX `default_index` (`number`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;
